# Distributed under the OSI-approved BSD 3-Clause License.  See accompanying
# file LICENSE

set(CMAKE_Arduino_OUTPUT_EXTENSION .o)

include(CMakeCommonLanguageInclude)

enable_language(CXX)

set(CMAKE_Arduino_CREATE_SHARED_LIBRARY ${CMAKE_CXX_CREATE_SHARED_LIBRARY})
set(CMAKE_Arduino_CREATE_SHARED_MODULE  ${CMAKE_CXX_CREATE_SHARED_MODULE})
set(CMAKE_Arduino_ARCHIVE_CREATE        ${CMAKE_CXX_ARCHIVE_CREATE})
set(CMAKE_Arduino_ARCHIVE_APPEND        ${CMAKE_CXX_ARCHIVE_APPEND})
set(CMAKE_Arduino_ARCHIVE_FINISH        ${CMAKE_CXX_ARCHIVE_FINISH})
set(CMAKE_Arduino_FLAGS                 ${CMAKE_CXX_FLAGS})
set(CMAKE_Arduino_FLAGS_RELEASE         ${CMAKE_CXX_FLAGS_RELEASE})
set(CMAKE_Arduino_FLAGS_RELWITHDEBINFO  ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
set(CMAKE_Arduino_FLAGS_MINSIZEREL      ${CMAKE_CXX_FLAGS_MINSIZEREL})
set(CMAKE_Arduino_FLAGS_DEBUG           ${CMAKE_CXX_FLAGS_DEBUG})

set(CMAKE_Arduino_COMPILE_OBJECT
    "<CMAKE_Arduino_COMPILER> -- <CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_Arduino_LINK_EXECUTABLE
    "<CMAKE_Arduino_COMPILER> -- <CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_Arduino_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

mark_as_advanced (
  CMAKE_BUILD_TOOL
  CMAKE_VERBOSE_MAKEFILE 
  CMAKE_Arduino_FLAGS
  CMAKE_Arduino_FLAGS_RELEASE
  CMAKE_Arduino_FLAGS_RELWITHDEBINFO
  CMAKE_Arduino_FLAGS_MINSIZEREL
  CMAKE_Arduino_FLAGS_DEBUG
)

set(CMAKE_Arduino_INFORMATION_LOADED 1)

